drop database flowercart;
CREATE DATABASE FLOWERCART;

USE FLOWERCART;
drop table enquiry;
CREATE TABLE ENQUIRY(
FULLNAME VARCHAR(30),
MOBILE VARCHAR(15),
EMAIL VARCHAR(30)
);

SELECT * FROM ENQUIRY;


CREATE TABLE USERS (
	FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    MOBILE VARCHAR(15),
    EMAIL VARCHAR(60) PRIMARY KEY
);
   
SELECT * FROM USERS;


CREATE TABLE CART(
	PID VARCHAR(10),
    PNAME VARCHAR(30),
    EMAIL VARCHAR(100),
    PPRICE VARCHAR(30),
    QTY VARCHAR(100)
);

SELECT * FROM CART;